### ISSUE TITLE
Add partial matches / various confidence levels

### ISSUE THREAD

**Issue by pwnfoo** [sachinkamath/fakemenot#11]
Right now, the app only checks if the confidence level is above a certain percentage. It'd be great to print the confidence level of all the images given and have various levels of confidence.

**Comment by ThrowsException** [comment]
I'd like to take a try at this

**Comment by pwnfoo** [comment]
@ThrowsException feel free to send in a PR :)

**Comment by ThrowsException** [comment]
What version of python do you use to run this?

**Comment by pwnfoo** [comment]
Keeping it as modular as possible. This will currently run in both 2.x and
3.x versions of Python :)

**Comment by ThrowsException** [comment]
I'm getting some conflicts. appears there are print statements written that will only work in python 2 right now. https://github.com/sachinkamath/fakemenot/blob/master/fakemenot/__init__.py#L36

Also there is an incompatibility with importing `configparser` as it stands in python2

**Comment by pwnfoo** [comment]
Ah, okay. My bad. You can work on Py2 for now. I'll fix it later :)

**Comment by ThrowsException** [comment]
Have a look https://github.com/sachinkamath/fakemenot/pull/14

**Comment by pwnfoo** [comment]
Fixed in #14 , thanks to @ThrowsException  💯
