### ISSUE TITLE
Ubuntu setup fail

### ISSUE THREAD

**Issue by abhinavralhan** [sachinkamath/fakemenot#17]
Running this on Ubuntu 16.04 LTS, as per the given setup. The package is not found.

sudo apt-get install tessearct-ocr tesseract-data-eng
[sudo] password for *user*: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package tessearct-ocr
E: Unable to locate package tesseract-data-eng

**Comment by pwnfoo** [comment]
@abhinavralhan Thanks for reporting. Please see the latest README :)
