### ISSUE TITLE
Complete setup.py to include installation

### ISSUE THREAD

**Issue by pwnfoo** [sachinkamath/fakemenot#2]
It'll be really nice to have the `setup.py` completed. It only install dependencies now.

**Comment by simocosimo** [comment]
What functions have you in mind? How the script should be completed? 
It would help me a lot if you give me some hints :)

**Comment by pwnfoo** [comment]
@simocosimo I'd love to have the program installed onto the system. If you're looking to start off with `setup.py`, [here is a great link from the Python Docs](https://docs.python.org/2/distutils/setupscript.html)

**Comment by omaciel** [comment]
Please see pull request #4

**Comment by pwnfoo** [comment]
This was fixed in #4. Thank you x2 @omaciel  :D

**Comment by omaciel** [comment]
My pleasure @sachinkamath :)
