### ISSUE TITLE
App fails to run

### ISSUE THREAD

**Issue by elahmo** [sachinkamath/fakemenot#22]
When running the app, this always (at least for me) occurs:

`ahmet  Desktop  fakemenot -i twitter.png
Detected handle : @elahmo
Traceback (most recent call last):
  File "/Users/ahmet/anaconda/bin/fakemenot", line 11, in <module>
    load_entry_point('fakemenot==0.0.3', 'console_scripts', 'fakemenot')()
  File "build/bdist.macosx-10.9-x86_64/egg/fakemenot/__init__.py", line 190, in main
  File "build/bdist.macosx-10.9-x86_64/egg/fakemenot/__init__.py", line 115, in _do_ocr_and_lookup
ValueError: 'v' is not in list`

The issue is at [this line](https://github.com/sachinkamath/fakemenot/blob/master/fakemenot/__init__.py#L113).

@sachinkamath can you tell us the reasoning by looking for this V? This is not always suggested by OCR, and a simple fix is to remove this check completely, and I did that in my repo, but wanted to see is there any reason for this.

**Comment by pwnfoo** [comment]
Hmm, that's a hack to detect the dropdown that appears on almost all of the desktop screenshots. I split the text based on that to pull the most possible body.

I shoud have seen this coming. Let me just go ahead and add an exception handler for that. Thanks for reporting :)

**Comment by elahmo** [comment]
For couple of my screenshots, there is no V/v in the OCR output, and since the matching looks at the text of the tweet from the API, any additional content that is detected from the picture won’t hurt, as it has the handle, date, and some characters afterwards, like the heart icon, etc. So this might be removed completely :)

**Comment by pwnfoo** [comment]
Sounds good. I added it to improve the accuracy calculation I have now. I will just add a `ValueError` exception handler to this and not split it if nothing is found.

**Comment by pwnfoo** [comment]
I've handled it [in my recent commit](https://github.com/sachinkamath/fakemenot/commit/22f37ca1011527ea0dffe2b6e378ae385e2f1120#diff-14d58a6d692c27d08d72f50af56da9d8R114) 💃
