### ISSUE TITLE
Limit confidence precision to 2

### ISSUE THREAD

**Issue by pwnfoo** [sachinkamath/fakemenot#6]
Convert the precision to 2 and add a nice % symbol next to it :)

**Comment by rjalfa** [comment]
https://github.com/sachinkamath/fakemenot/blob/dfb9f42e9f2a345ec8ed50b943cf3e3aa772ce33/fakemenot/__init__.py#L81
^ On this line?

**Comment by kuldipkumark** [comment]
Done, please review #7.

**Comment by pwnfoo** [comment]
Fixed in #7
