### ISSUE TITLE
Handle the twitter configuration file

### ISSUE THREAD

**Issue by pwnfoo** [sachinkamath/fakemenot#8]
We recently moved to `setup.py` based installation and it looks like a thing or two broke.

The file `fakemenot/twitter.config` needs to be handled now. There are multiple ways to handle this. 
* Ask the user to keep the file in homedir, something like `.twitterconfig` and read it.
* Pass the configuration file using an argument, say `-c`.
* Handle the file during the installation itself.

**Comment by pcn** [comment]
I took a stab at it in https://github.com/sachinkamath/fakemenot/pull/9

**Comment by pwnfoo** [comment]
Thanks x2 @pcn. Fixed in #9
